### ISSUE TITLE
Clarify CommandLineRunner in Application.java

### ISSUE THREAD

**Issue by gregturn** [spring-guides/tut-bookmarks#10]
[Copied in from personal blog comment]
Hello Greg,

A great tutorial on Spring REST with Spring Boot (http://spring.io/guides/tutorials/bookmarks/). I have a question that requires the clarity. In "Application.java", how does the line that has "return (evt) -&gt; ..." returns the CommandLineRunner type? I was searching for everywhere how this works but most point to "implements CommandLineRunner" format...

**Comment by gregturn** [comment]
If you look at http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/CommandLineRunner.html#run(java.lang.String...), you'll see that this interface has a single method that accepts an array of strings. The tutorial's Application class takes advantage of Java 8's ability to coerve a lambda function call into a CommandLineRunner. As the paragraph right below the code states, Spring Boot will run any and all CommandLineRunners after the application context is created. If you look on YouTube for one of Josh Long's (the author of this tutorial) videos on "Bootiful Apps", you'll see him illustrate this same concept.

**Comment by qiaosangning** [comment]
Yes, i got  it at last. It is about the functional Interface and lambda expression of Java8. First, we should known what is functional interface, then we will learn how lambda expressiom implements the funcitonal interface. "CommandLineRunner" interface is a functional interface, then we use lambda expression to implements it.
