### ISSUE TITLE
Tutorial has insufficient Spring initializer projects

### ISSUE THREAD

**Issue by amitch** [spring-guides/tut-bookmarks#12]
Tutorial has insufficient information to executre, this includes Spring initializer projects, " In this case, we’re going to build a web application. So, select "Web" and then choose "Generate." A .zip will start downloading". It needs atleast JPA, some embedded DB  H2 and likely others incl. HATEOS visible via advanced link below.
And there is no step for mvn spring-boot:run

**Comment by JetForMe** [comment]
I've run into this problem, as well. It also needs some instructions for launching the app from the command line (I'll write up a separate issue for this).

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-bookmarks/commit/d5c8076cfd6ed4799cc5fa1c10a4959a9c48c665
