### ISSUE TITLE
Question: @RestController with ResponseEntity

### ISSUE THREAD

**Issue by DanailMinchev** [spring-guides/tut-bookmarks#22]
Hi,

I was wondering if it's the best practice to use `@RestController` with `ResponseEntity` when we need more flexibility (for example to return more than one HTTP status code)?

The concrete example in the code: https://github.com/spring-guides/tut-bookmarks/blob/a5b4d43d63d3c7d8a6107873841526f92d7bad2d/rest/src/main/java/bookmarks/BookmarkRestController.java#L56

Basically, I can see that in this project `@RestController` is used everywhere, but also I can see that it is used with `ResponseEntity` (see example above).

Is it ok to do so? I am asking just to confirm my response from here: http://stackoverflow.com/questions/26549379/when-use-responseentityt-and-restcontroller-for-spring-restful-applications/40454751#40454751

Thank you very much!

**Comment by gregturn** [comment]
If you mean contextually returning different HTTP response codes, then that is exactly what `ResponseEntity<?>` with the `?` generic type is for.

You can have the main service call `ResponseEntity.ok()`, but in the event of an exception, use an alternative code.

Or you can return different types if that is really needed. ResponseEntity is just a generic container that includes headers, body, and HTTP status code. It's not a requirement, but quite handy in many cases.

**Comment by DanailMinchev** [comment]
@gregturn thank you for your quick response,

Yes, I understand that, maybe I wasn't that clear, my question is:
Is it ok to use `ResponseEntity` with `@RestController`? Because `@RestController` itself adds `@ResponseBody` annotation and `ResponseEntity` with `@ResponseBody` might be in conflict (because they both can be used to return the HTTP body)? Thanks

**Comment by gregturn** [comment]
ResponseEntity and `@ResponseBody` aren't related. The former is a container for return types. The latter signals Spring MVC to write the results into the HTTP response body.

`@ResponseBody` doesn't have any parameters, so I'm not sure what you are getting at.
