### ISSUE TITLE
HATEOAS class BookmarkRestController @RequestMapping(method = RequestMethod.POST)

### ISSUE THREAD

**Issue by Coroecram** [spring-guides/tut-bookmarks#38]
Getting the error: Cannot infer type argument(s) for <U> map(Function<? super T,? extends U>
For 		return accountRepository.findByUsername(userId)
            .map(account -> {
                Bookmark bookmark = bookmarkRepository
                        .save(new Bookmark(account, input.uri, input.description));

                Link forOneBookmark = new BookmarkResource(bookmark).getLink("self");

                return ResponseEntity.created(URI.create(forOneBookmark.getHref())).build();
            })

Will continue debugging.

**Comment by Coroecram** [comment]
Try to type some things here, backspace there, and it compiles correctly for seemingly no reason. Maybe an extra space? But I copied and pasted. *sigh*

**Comment by TommySedin** [comment]
Just in case someone else stumbles on this error; For me, this error was actually a side-effect of missing imports. Adding all necessary imports resolved this.
