### ISSUE TITLE
"Invalid derived query! No property accountUsername found for type Bookmark" error in STS

### ISSUE THREAD

**Issue by urig** [spring-guides/tut-bookmarks#48]
When following the tutorial in STS, when I get to the `BookmarkRepository` the line

    Collection<Bookmark> findByAccountUsername(String username);

Gives the error:
> Invalid derived query! No property accountUsername found for type Bookmark

Looks like it's missing a @Query attribute, based on this SO answer: https://stackoverflow.com/a/35129939/33404

**Comment by gregturn** [comment]
Problem seems to have vanished. I have run this in IntelliJ as well as on the command line, and see now such issue.
