### ISSUE TITLE
Tutorial text does not mention including Spring Security Starter

### ISSUE THREAD

**Issue by SpaceOso** [spring-guides/tut-bookmarks#50]
New to Spring Boot and Java and following the tutorial step by step.

IntelliJ threw errors about not finding symbols: GlobalAuthenticationConfigurerAdapter and AuthorizationServerConfigurerAdapter

I spent time trying to figure this out and I believe I needed to include spring security to my pom file. Adding it fixed GlobalAuthenticationConfigurerAdapter.

But I'm still trying to figure out GlobalAuthenticationConfigurerAdapter.

The tutorial does not mention to include spring-security when using the initilizer.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-bookmarks/commit/9294e95ec6d03d115ba4d6572cd235de4789b8d0
